# Generated by Django 3.2.24 on 2024-03-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240304_2220'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dream_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.dreamcenter', verbose_name='Dream Center'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Answered?'),
        ),
    ]
